#!/bin/bash

echo "🎯 Test du système parrainage"
echo "Ouvre reductions.html :"
echo "https://anduxara2408-droid.github.io/andu-xara-site/reductions.html"
echo ""
echo "=== 🧪 CODE POUR LA CONSOLE ==="
echo "Colle ce code dans la console du navigateur :"
echo ""
echo "// Test système parrainage"
echo "console.log('=== TEST ANDU XARA ===');"
echo "const section = document.getElementById('andu-xara-parrainage-final');"
echo "const fonction = typeof anduGenererLien;"
echo "console.log('Section:', section ? '✅ TROUVÉE' : '❌ MANQUANTE');"
echo "console.log('Fonction:', fonction === 'function' ? '✅ PRÉSENTE' : '❌ MANQUANTE');"
echo "if (section) {"
echo "  section.style.border = '4px solid green';"
echo "  console.log('✅ Section highlightée en vert');"
echo "}"
echo "// Test Firebase"
echo "console.log('Firebase:', typeof db !== 'undefined' ? '✅ CHARGÉ' : '❌ MANQUANT');"
echo "console.log('Auth:', typeof getCurrentUser !== 'undefined' ? '✅ PRÉSENT' : '❌ MANQUANT');"
